apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: g46-reviews
  name: g46-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: g46-reviews
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: g46-reviews
    spec:
      containers:
        - env:
            - name: SERVICE_VERSION
              value: "v3"
            - name: ENABLE_RATINGS
              value: "true"
            - name: STAR_COLOR
              value: "red"
          image: tracert007/reviews
          name: g46-reviews
          ports:
            - containerPort: 9080
          resources: {}
      restartPolicy: Always
status: {}
