apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: g46-ratings
  name: g46-ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: g46-ratings
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: g46-ratings
    spec:
      containers:
        - env:
            - name: SERVICE_VERSION
              value: v1
          image: tracert007/ratings
          name: g46-ratings
          ports:
            - containerPort: 9080
          resources: {}
      restartPolicy: Always
status: {}
