apiVersion: v1
kind: Service
metadata:
  name: details
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: g46-details
    name: g46-details
spec:
  ports:
    - name: "9080"
      port: 9080
      targetPort: 9080
  selector:
    io.kompose.service: g46-details
status:
  loadBalancer: {}
