FROM python:3.7.7-slim

RUN apt-get update && apt-get install -y git

WORKDIR /opt/monolitica/

RUN git clone https://github.com/huzmgod/CDPSp2.git .

WORKDIR /opt/monolitica/bookinfo/src/productpage/

COPY . .

RUN pip3 install -r requirements.txt
EXPOSE 9080

CMD ["python3", "productpage_monolith.py", "9080"]
